-- Fix whatsapp_sessions table schema
-- Execute este script no SQL Editor do Supabase

-- Adicionar colunas que faltam
ALTER TABLE whatsapp_sessions
ADD COLUMN IF NOT EXISTS name TEXT;

ALTER TABLE whatsapp_sessions
ADD COLUMN IF NOT EXISTS session_id TEXT UNIQUE;

ALTER TABLE whatsapp_sessions
ADD COLUMN IF NOT EXISTS phone_number TEXT;

ALTER TABLE whatsapp_sessions
ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'disconnected';

ALTER TABLE whatsapp_sessions
ADD COLUMN IF NOT EXISTS qr_code TEXT;

ALTER TABLE whatsapp_sessions
ADD COLUMN IF NOT EXISTS last_connected TIMESTAMP;

ALTER TABLE whatsapp_sessions
ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE;

-- Se precisar criar a tabela do zero (caso não exista):
-- DROP TABLE IF EXISTS whatsapp_sessions;
-- 
-- CREATE TABLE whatsapp_sessions (
--   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--   session_id TEXT UNIQUE NOT NULL,
--   name TEXT NOT NULL,
--   phone_number TEXT,
--   status TEXT DEFAULT 'disconnected',
--   qr_code TEXT,
--   last_connected TIMESTAMP,
--   is_active BOOLEAN DEFAULT TRUE,
--   created_at TIMESTAMP DEFAULT NOW()
-- );

-- Verificar se funcionou
SELECT column_name, data_type 
FROM information_schema.columns 
WHERE table_name = 'whatsapp_sessions'
ORDER BY ordinal_position;
